### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by jgentes** [alexkuz/react-base16-styling#1]
`$ npm i -S react-base16-styling`
`npm WARN deprecated husl@5.0.3: Project renamed to HSLuv`

Not sure if the deprecation warning is the cause of the failure or not, but it's the only thing abnormal in the log.

**Comment by alexkuz** [comment]
@jgentes it does show a warning, but I don't see a failure. Can you share some details - node version, `npm-debug.log` (if there is one) etc.?

**Comment by jgentes** [comment]
I was trying to install this to get themes for a react json tree viewer, but then realized I could just inline the styles in the component, so I didn't follow up on this. Sorry about not being able to provide more data. It's possible the issue was unrelated to your module, so I'll go ahead and close this.
